USEPA/webcms

services/drupal/web/modules/custom/epa_workflow/epa_workflow.module
Change assertion message as follows:
'#title' => I certify that this page complies with:
'#description' => all applicable Section 508 requirements and EPA's External Site Links Procedure. This page will be subject to random external site link reviews by the Office of Web Communications andSection508 compliance reviews by the Environmental Information. Non-compliant pages will be unpublished until remediated.
=> EPAD8-886: weak 508 Assertions on Content

infrastructure/terraform/cluster.tf
This PR makes two autoscaling group changes:
1. We add additional servers at 75% capacity utilization instead of 100%, and
2. A minimum of two servers must be added to the cluster.
Load testing results indicated that the autoscaling group is a bottleneck under load - the capacity provider would only increment the number of required EC2s by one each time, effectively throttling the rate at which we can add tasks to the cluster. The first change means we initiate scaling sooner, and the second change ensures that we can add a larger number of tasks at one time.
**Deployment notes:** We may need to manually intervene in Terraform if it can't delete the current capacity provider.
=> Scale EC2s at 75% capacity instead of 100%

infrastructure/terraform/cluster.tf
By forcing Terraform to create a new capacity provider before destroying the old one, we should be able to avoid considerable downtime if/when we need to replace capacity providers in the future.
=> Create capacity providers before destroying

infrastructure/terraform/alb.tf, infrastructure/terraform/providers.tf
During load testing, we saw that CPU load wasn't spread evenly across ECS tasks. This change requests that the load balancer distribute requests across tasks such that the task with the least amount of requests is prioritized, rather than the default (a round-robin strategy).
=> Use least outstanding requests for load balancer strategy

.buildkite/run-drush.sh
In cases where Drush exits due to an external signal (SIGSEGV being the most recent example), the Buildkite script will now print the signal name so we know what happened.
=> Print exit signal for debugging purposes

infrastructure/terraform/alb.tf
This changes the health check interval to once every five minutes.
=> Use more lenient interval for ALB health checks

services/drupal/config/sync/migrate_plus.migration.upgrade_d7_node_revision_web_area_panelizer.yml, services/drupal/config/sync/migrate_plus.migration.upgrade_d7_node_revision_web_area_paragraph_banner.yml, services/drupal/config/sync/migrate_plus.migration.upgrade_d7_node_web_area_panelizer.yml, services/drupal/config/sync/migrate_plus.migration.upgrade_d7_node_web_area_paragraph_banner.yml, services/drupal/web/modules/custom/epa_migrations/config/install/migrate_plus.migration.upgrade_d7_node_revision_web_area_panelizer.yml, services/drupal/web/modules/custom/epa_migrations/config/install/migrate_plus.migration.upgrade_d7_node_revision_web_area_paragraph_banner.yml, services/drupal/web/modules/custom/epa_migrations/config/install/migrate_plus.migration.upgrade_d7_node_web_area_panelizer.yml
I was using the 'node_revision' source plugin to create web area homepage banner paragraphs for all nodes. It turns out this source plugin excludes the current revision. To resolve, I added additional configuration to process homepage banner paragraphs separately for node (current revisions) and node revisions.
=> [EPAD8]  Create banner slides for nodes and node revisions separately

infrastructure/terraform/utility.tf
This updates the SQL dump script to automatically compress the dump file. Dumps of the staging database are over 1GB compressed now, so it's worth compressing these to save on storage space and transfer time.
=> Compress DB dumps on the utility instance

infrastructure/terraform/alb.tf, infrastructure/terraform/variables.tf
This PR changes the `alb-hostname` variable into an optional list of strings for other host names to match against incoming requests.
=> Allow load balancer to respond to other hostnames

infrastructure/terraform/cron.tf, infrastructure/terraform/shared.tf, infrastructure/terraform/variables.tf, services/drupal/.env.example, services/drupal/web/modules/custom/epa_core/epa_core.services.yml, services/drupal/web/modules/custom/epa_core/src/Config/EpaCoreOverrider.php, services/drupal/web/sites/default/settings.local.env.php, services/drupal/web/sites/default/settings.php
I'm parameterizing the port and protocol (Gopa asked for this).  I also provided a new setting to disable the sending of workflow notifications so that we could allow emailing to work in general without having to have all those emails get sent.  Please take a look and let me know what you think.
(And yes, the --debug flag for cron snuck in there but I'm not bothering to refactor).
=> Epad8 730 paramaterize email further

infrastructure/terraform/cloudwatch.tf
This PR addresses an issue in which we accidentally used the wrong keyword for overriding the statistic.
=> EPAD8-777: Fix data issue

.buildkite/deploy.yml, .buildkite/pipeline.yml
This fixes a small number of issues:
* Builds to `main` and `integration` were running the feature pipeline
* The `terraform output` command was only partially complete and thus failed the Terraform run
* Docker image builds during a deployment are limited by environment, allowing the staging and Spanish-language environments to build images at the same time.
=> EPAD8-966: Address deployment issues 

services/drupal/web/themes/epa_theme/epa_theme.libraries.yml, services/drupal/web/themes/epa_theme/js/src/media-link.es6.js, services/drupal/web/themes/epa_theme/source/_meta/_01-foot.twig, services/drupal/web/themes/epa_theme/source/_patterns/05-components/external-link/external-link--image/_external-link--image.scss, services/drupal/web/themes/epa_theme/source/_patterns/05-components/figure/_figure.scss, services/drupal/web/themes/epa_theme/source/_patterns/05-components/figure/figure.twig, services/drupal/web/themes/epa_theme/source/wysiwyg.scss, services/drupal/web/themes/epa_theme/templates/media/media.html.twig
This PR will:
- Clean up WYSIWYG styles for the CKEditor focus outlines when applied to media embeds
- Add JS to move `<a>` that wraps figures to wrap the inner `<img>` instead
- Fix external image link styles when applied to figures
=> EPAD8-933: Media embeds

infrastructure/terraform/cluster.tf, infrastructure/terraform/migration.tf
This PR adds an additional capacity provider to the ECS cluster. This capacity provider is an autoscaling group of metal instances (max size 1) in order to get the highest clock rate from AWS instances.
This capacity provider is used nowhere by default; migration scripts will need to explicitly opt in to this capacity provider by altering the `RunTask` overrides (documentation to follow).
=> Add migration-specific capacity provider

.buildkite/pipeline.yml
This conditional was causing the feature pipeline to be evaluated for main and integration, since the `||` operator made the condition true for all cases.
=> Fix wrong operator in feature conditional

.buildkite/run-drush.sh
Our AWS account has been upgraded to a new task ARN format. This affects the `run-drush.sh` script as the new ARN format has an extra slash, so the parsing has to be adjusted.
=> Account for new ARN format

infrastructure/terraform/rds.tf
This PR adds extra collection from the MySQL server:
1. It enables the slow query log, which triggers on two conditions:
1. Queries that take longer than 125ms. This is an extremely aggressive threshold that should be tuned lower once our migration testing is completed, but it will gives us more data in the meantime.
2. Any query that does not use indexes. We are seeing MySQL perform joins that require full table scans, and logging this queries will allow us to tune anything causing trouble.
2. It enables MySQL's performance schema (see this [quick start](https://dev.mysql.com/doc/refman/5.7/en/performance-schema-quick-start.html)) to augment our usage of RDS performance insights.
**Deployment note**: Enabling these features requires a restart of the Aurora cluster instances. We will need …
=> Enable extra performance data collection in Aurora MySQL

infrastructure/terraform/alb.tf, infrastructure/terraform/s3.tf
This PR enables logging at the load balancer level. Logs are uploaded to S3 for offline ingestion, rather than in CloudWatch.
=> EPAD8-998: Enable ALB logs

infrastructure/terraform/s3.tf
This PR ignores the initial attempts to use `random_id` and just generates a bucket using Terraform's prefix option.
=> EPAD8-998: ELB logs

infrastructure/terraform/alb.tf, infrastructure/terraform/s3.tf
Per the [AWS documentation](https://docs.aws.amazon.com/elasticloadbalancing/latest/application/load-balancer-access-logs.html#access-logging-bucket-permissions), we need to explicitly grant the load balancing service permission to deliver logs to the logging bucket. This PR creates the necessary permission policy and applies it to the ELB logs bucket.
=> EPAD8-998: Grant log delivery permission

infrastructure/terraform/variables.tf, infrastructure/terraform/vpc.tf
In deployments using a shared VPC, we can't unconditionally create interface endpoints for SSM and EC2. There can only be one endpoint for a service in a VPC. This PR adds a variable, `vpc-create-interfaces`, to control the creation of the endpoint interfaces.
Initial testing has indicated that this does not apply to the S3 gateway (it uses a different mechanism that doesn't cause the overlap problem), so we can continue to create it in the VPC as normal.
=> Make interface creation optional

infrastructure/terraform/cluster.tf, infrastructure/terraform/migration.tf
This PR re-enables the migration capacity provider.
(This is a revert of commit b79978964c15dc4ed83b2469a416743cad51ee19.)
=> Re-enable the migration capacity provider

services/drupal/web/modules/custom/epa_migrations/src/EpaWysiwygTextProcessingTrait.php
Adding this check will hopefully avoid the 'element not found' error I saw during a test run of the basic page revision migration. I believe there's a possible case where we find an element to remove, but its parent ends up getting removed during the 'removeEmptyTextNodes' method.﻿
=> [EPAD8-965] Check to make sure element to remove exists

infrastructure/terraform/utility.tf
Add a block_device_mapping for the utility instances to provide a disk with 32GB of space. The default instance disk space is too small to hold a Stage database dump with migrated data.
Once this is merged and the build finishes, an SRE will need to terminate the existing utility instance so AWS will deploy a fresh one with the new block storage.
=> Create block device mapping for utility instances

services/drupal/web/themes/epa_theme/source/_patterns/05-components/menu/menu--main/_menu--main.scss
@dcmouyard : we noticed that there was no indicator of the active page in the main menu
=> Add styling to is-active main-menu link

infrastructure/terraform/automation.tf, infrastructure/terraform/iam.tf, infrastructure/terraform/logging.tf, infrastructure/terraform/proxy.tf, infrastructure/terraform/s3.tf, infrastructure/terraform/shared.tf
This PR creates a pair of Systems Manager automation documents to interact with the database. Normally, these would be handled as ECS tasks, but there are a few limitations that we've run into:
1. `drush sqlc` imposes a timeout, and loading database dumps of this magnitude trip that limit; and
2. The database dumps themselves are large enough that they will exhaust Fargate task storage (this will be improved in 1.4.0, but we may still need to be wary).
With these factors in mind, we are using SSM automation to spawn temporary EC2 instances with a large enough root volume to handle both compressed and uncompressed database dumps. Decompressed, these dumps can be over 12GiB in size.
The general structure of both automation documents is as follows:
1. Spawn an EC2 instance in the cluster's …
=> EPAD8-1016: Systems Manager automation documents

infrastructure/terraform/automation.tf, infrastructure/terraform/security.tf
This fixes two bugs in the automation documents:
1. Incorrect capitalization of `executionTimeout`, and
2. The automated instances were not able to access AWS Secrets Manager and thus would wait almost indefinitely for a connection that could never complete.
=> EPAD8-1016: Automation fixes

infrastructure/terraform/automation.tf
For some reason, the API for updating automation documents is now failing when updating the documents. This PR uses a small random identifier to force them to be recreated instead of updated in place.
=> EPAD8-1016: Force Terraform to recreate documents

services/drupal/Dockerfile, services/drupal/scripts/ecs/drush-migrate.sh
This PR introduces a Bash script to run migrations unattended in Fargate. The script is available as `drush-migrate` in `$PATH`, meaning it's possible to run the full gamut of migrations as an entrypoint override with `aws ecs run-task`.
=> Add Bash script for unattended migrations

services/drupal/web/modules/custom/epa_migrations/src/Plugin/migrate/source/EpaOgMenuLink.php
This raises migration count from 4388 to 4477, as expected.
=> [EPAD8-1021] Don't use heuristic to find group menu names

services/drupal/scripts/ecs/drush-migrate.sh
All migrations should expect to have 0 unprocessed items.
=> Update expected_unprocessed for 4th dry run

scripts/halt-stage-migration.sh, scripts/stage-command.sh.example, scripts/start-stage-migration.sh, services/drupal/scripts/ecs/drush-migrate.sh
This allows us to re-run the script without needlessly rerunning
all batches that do nothing.
Also fixes the fargate config in tasks.
=> Calculate batches by unprocessed, not total

scripts/allow-unprocessed.sh, scripts/halt-stage-migration.sh, scripts/stage-command.sh.example, services/drupal/scripts/ecs/drush-migrate.sh
Eliminates need for 20+ minute build to update allowed counts and restart migration.
=> Allow setting allowable unprocessed counts without a build

services/drupal/config/sync/migrate_plus.migration.upgrade_d7_node_web_area_paragraph_banner_slide.yml, services/drupal/web/modules/custom/epa_migrations/config/install/migrate_plus.migration.upgrade_d7_node_web_area_paragraph_banner_slide.yml, services/drupal/web/modules/custom/epa_migrations/src/Plugin/migrate/source/EpaMultivalueField.php
Please take a look at this and tell me what you think.  We missed some records in the upgrade_d7_node_web_area_paragraph_banner_slide migration due to the fact that we used the revision ID as the high water mark.  Revision ID isn't unique since there can be multiple field values attached to a single revision with different deltas.  This change adds an expression that concatenates revision ID and delta to achieve a truly unique value to be used as the Highwater mark.
=> Fix high water mark on our banner migration to ensure all get migrated

.buildkite/run-drush.sh
This PR makes a few changes to `run-drush.sh`:
1. It limits the output of `aws ecs stop-task` to just the task ARNs that were stopped. This is mostly useful when testing the `run-drush.sh` script locally.
2. It prevents `xargs` from iterating over an empty list of tasks during the stop task phase. This could happen if many builds occurred very close to each other, and ECS didn't yet have time to spawn new tasks for the Drupal service.
3. The output of `aws ecs run-task` is now inspected for failures before waiting on a newly-spawned task. Note that this failure mode applies only to API failures; if RunTask itself returns an error, then it means that AWS was unable to complete our request (due to, e.g., bad permissions).
=> Catch ECS RunTask errors during Drush updates

services/drupal/web/modules/custom/epa_migrations/src/EpaMediaWysiwygTransformTrait.php
`\\\"""` is not a valid empty string, rewrite as `""`.
You can find several malformed instances in `field_data_body.body_value` via this query:
```
SELECT COUNT(1) FROM field_data_body WHERE body_value LIKE '%"alt":"\\\\\\"""%' ESCAPE '$';
```
=> Fix corrupted JSON in some media embeds

infrastructure/terraform/vpc.tf
Not totally certain why this parameter is now needed, but this addresses the build failures.
=> Fix Terraform plan error

services/drupal/config/sync/migrate_plus.migration.upgrade_d7_group_content_file.yml, services/drupal/config/sync/migrate_plus.migration.upgrade_d7_node_web_area_paragraph_banner_slide.yml, services/drupal/web/modules/custom/epa_migrations/config/install/migrate_plus.migration.upgrade_d7_group_content_file.yml
When I uninstalled and re-installed the epa migrations module locally, these config changes were detected. I split them into a separate PR because I'm not familiar with the `use_og_table` source setting and wanted to make sure this is a desired change.
=> [EPAD8] Migration config cruft

services/drupal/web/modules/custom/epa_migrations/src/Plugin/migrate/source/EpaPanelizerNode.php, services/drupal/web/modules/custom/epa_migrations/src/Plugin/migrate/source/EpaPanelizerNodeRevision.php
I updated the EpaPanelizerNode and EpaPanelizerNodeRevision source queries to be in alignment with the updates made to the non-panelizer source plugins. Testing locally, I checked that the number of revisions that exist for Basic Pages and Documents matches the numbers that are returned for the revision migrations on the migration status page.
=> [EPAD8] Update panelizer source queries

services/drupal/web/modules/custom/epa_migrations/src/Plugin/migrate/process/EpaSetLatestRevision.php
In migration 5, we saw that nodes were not getting the correct revision set as the current revision. This is because we moved the call to `$this->pathautoOn($node);` to happen after the logic to set the latest and current revision. Since we were passing the `pathautoOn` method the same `$node` variable that we instantiated at the start of the process, the variable had outdated entity data. When we called `$node->save()` in the `pathautoOn` method, we were re-saving the node with an outdated value for the current revision id.
This PR ensures we re-load the node entity prior to calling `pathautoOn` so that we're re-saving the entity with the correct values.
=> [EPAD8] Ensure we're passing the latest node entity to the pathauto method

services/drupal/scripts/ecs/drush-migrate.sh
We're not relying on migration dependencies, we're running our migration manually in the order needed. This will prevent the migration from stopping when any implied dependencies are not met.
=> Add `--force` flag to migrate import

services/drupal/config/sync/samlauth.authentication.yml, services/drupal/web/modules/custom/epa_migrations/src/Plugin/migrate/destination/EpaUserGroupMembership.php
This code is meant to add entries to the authmap table to establish the correct mapping between Drupal and SAML users.  You can test this by running the user migration and ensuring that entries are created in the authmap table.
=> Epad8 1233 migrate authmap

services/drupal/web/themes/epa_theme/source/_patterns/02-base/02-html-elements/16-blockquote/_blockquote.scss, services/drupal/web/themes/epa_theme/source/_patterns/05-components/pull-quote/_pull-quote.scss
@dcmouyard : is this the right way to make all `blockquote`s look like pull quotes? We find the default `blockquote` styling to be a little jarring, and we're finding that people have been using `blockquote`s a lot.
=> Apply pull quote style to blockquotes generally

terraform/infrastructure/traefik_service.tf, terraform/infrastructure/variables.tf
Per our load test results, this PR adds a scaling policy to the Traefik service to prevent it from being a bottleneck during high-load situations.
=> EPAD8-1338: Add CPU-based scaling policy for Traefik

services/drupal/web/modules/custom/epa_migrations/src/Plugin/migrate/source/EpaMultivalueField.php
I double-checked that our initializeIterator method is still in sync with the method provided in sqlBase.﻿
=> Remove warning about ensuring method is in sync with parent

.buildkite/infrastructure.yml, .gitlab-ci.yml, services/drupal/Dockerfile, services/drupal/scripts/ecs/drupal-entrypoint.sh, terraform/infrastructure/ecr.tf, terraform/infrastructure/logging.tf, terraform/infrastructure/parameters.tf, terraform/infrastructure/secrets.tf, terraform/webcms/drupal.tf, terraform/webcms/drush.tf, terraform/webcms/shared.tf
This PR adds the infrastructure needed to monitor the WebCMS with New Relic. Specifically:
1. In the infrastructure Terraform:
1. The New Relic PHP daemon is mirrored in ECR, much like Traefik and the CloudWatch agent.
2. The daemon has a new log group created for it.
3. A new Secrets Manager secret has been created for the license key. In order to avoid breaking existing deployments, a default value of `""` is deployed by Terraform. Changes to this value are ignored and Terraform won't revert them.
2. In the WebCMS Terraform:
1. The New Relic daemon is available for both web-facing Drupal and command-line Drush workloads.
2. A new startup scripts detects the presence of a New Relic license key in the environment and, if it is available, enables the extension.
When a New Relic license key …
=> EPAD8-1175: Install New Relic extension

services/drupal/scripts/ecs/drupal-entrypoint.sh, terraform/infrastructure/secrets.tf
The AWS API documentation isn't particularly clear about whether or not empty strings are allowed, but Terraform is failing with an API error. I've changed the default value to the string `'.'` in order to unblock these failing deployments.
=> EPAD8-1175: Work around API requirements

services/drupal/Dockerfile, services/drupal/scripts/ecs/drupal-entrypoint.sh
It appears that by setting an image's `ENTRYPOINT`, we remove the `CMD` we had been inheriting from our upstream image. This PR adds that in place, and also has more logging in the entrypoint in order to see how much progress we make before an exit.
=> EPAD8-1175: Fix accidental removal of CMD

services/drupal/scripts/ecs/drupal-entrypoint.sh
Since we use `/` characters in the WebCMS application name, we need to use other delimiters in the sed expression that updates `newrelic.ini`.
=> EPAD8-1175: Use non-conflicting sed characters

infrastructure/terraform/iam.tf, services/drupal/web/modules/custom/epa_cloudwatch/epa_cloudwatch.services.yml, services/drupal/web/modules/custom/epa_cloudwatch/src/EventSubscriber/LogFlushSubscriber.php, services/drupal/web/modules/custom/epa_cloudwatch/src/Logger/CloudWatch.php
This PR changes our logging logic so that the logger defers publishing log events until after the response has been sent to the client. We also listen for console exits to publish logs for Drush.
=> Defer pushing CloudWatch logs until kernel terminate

services/drupal/web/themes/epa_theme/source/_patterns/05-components/figure/_figure.scss, services/drupal/web/themes/epa_theme/source/_patterns/05-components/figure/figure--video/_figure--video.scss
Moved the width: 100% to the .figure--video variation instead of globally on the Figure component
=> EPAD8-1322 auto width except for figure--video

services/drupal/composer.lock, services/drupal/composer.patches.json
Found a patch for the issue we were experiencing here https://www.drupal.org/project/drupal/issues/2839344
Currently fixed by the patch referenced in #17 within that link. Tested locally and the error for that aria attribute did not fire when tested, and appears to not exist when that element does not exist.
=> [EPAD8-1238] Apply patch for aria-describedby in radios and checkboxes

services/drupal/config/sync/core.extension.yml
This PR enables the late runtime processor for purge. This will add an event subscriber for every "FINISH_REQUEST" kernel event that will grab a chunk of cache tags from the queue and send them to Akamai for invalidation. This event is the same event we're using for the EPA Cloudwatch module. Authenticated users should not see a noticeable slowdown of the site, but we should gain a lot of purge queue processing.
=> [EPAD8-1369] Enable the purge late runtime processor

terraform/webcms/drupal.tf
Scale out at 40% CPU and increase minimum tasks during business hours to 25
=> Adjust min task and autoscale parameters

services/drupal/composer.patches.json
Updating patch used to resolve issue when changing a node's group causes a resave of the entity causing a fatal duplicate key database error.
=> [EPAD8-1471] Updating patch to allow moving nodes between groups

services/drupal/config/sync/user.role.authenticated.yml
This permission introduced in Drupal 9.2.x
=> Update AU permission to allow viewing email address

services/drupal/config/sync/webform.settings.yml
Webforms needs to allow mixed letter casing at /admin/structure/webform/config/elements (see https://www.drupal.org/project/webform/issues/3153965) - Letters, numbers, and underscores
=> Update webform settings to allow UPPERCASE element keys

services/drupal/status.conf, terraform/infrastructure/README.md, terraform/infrastructure/load_balancer.tf, terraform/infrastructure/parameters.tf, terraform/infrastructure/shared.tf, terraform/infrastructure/variables.tf, terraform/network/README.md, terraform/network/parameters.tf, terraform/network/security.tf, terraform/webcms/README.md, terraform/webcms/drupal.tf, terraform/webcms/shared.tf, terraform/webcms/target_group.tf
This PR adds an ALB behind the existing NLB. This is the first half of the migration away from Traefik; the second will be done after the ALB is deployed in order to minimize disruption. There is a new VPC security group required for the ALB. Its requirements are documented in the `terraform/network` module, and it has implications on the existing Drupal VPC security group.
=> Add ALB to ECS cluster

terraform/infrastructure/load_balancer.tf
We saw the following two errors when trying to apply this terraform:
Error: Error modifying LB Listener: ValidationError: An SSL policy cannot be specifed for TCP listeners
status code: 400, request id: eafb1313-d07b-4b1a-b761-27209e181d69
on load_balancer.tf line 48, in resource "aws_lb_listener" "https":
48: resource "aws_lb_listener" "https" {
Error: vpc_id should be set when target type is ip
on load_balancer.tf line 110, in resource "aws_lb_target_group" "alb_http":
110: resource "aws_lb_target_group" "alb_http" {
=> Two changes to correct errors in the terraform apply step:

services/drupal/web/themes/epa_theme/templates/content/node--event--full.html.twig, services/drupal/web/themes/epa_theme/templates/content/node--faq--full.html.twig, services/drupal/web/themes/epa_theme/templates/content/node--full.html.twig, services/drupal/web/themes/epa_theme/templates/content/node--news-release--full.html.twig, services/drupal/web/themes/epa_theme/templates/content/node--perspective--full.html.twig, services/drupal/web/themes/epa_theme/templates/content/node--public-notice--full.html.twig, services/drupal/web/themes/epa_theme/templates/content/node--regulation--full.html.twig, services/drupal/web/themes/epa_theme/templates/content/node--web-area.html.twig, services/drupal/web/themes/epa_theme/templates/layout/region--messages.html.twig, services/drupal/web/themes/epa_theme/templates/views/views-view--search-faqs.html.twig, services/drupal/web/themes/epa_theme/templates/views/views-view--search-news-releases.html.twig, services/drupal/web/themes/epa_theme/templates/views/views-view--search-perspectives.html.twig, services/drupal/web/themes/epa_theme/templates/views/views-view--search-public-notices.html.twig
This PR undoes some of the work in #607 in favor of an approach that correctly checks if Twig variables have markup that should be output.
=> EPAD8-1641: Admin info tweak

.buildkite/webcms.yml
This PR fixes a YAML syntax goof with the [Buildkite matrix](https://buildkite.com/docs/pipelines/build-matrix) in `.buildkite/webcms.yml`. Without the quotes, the `{{matrix}}` interpolation is treated as a dictionary of some kind.
=> EPAD8-1271: Quote matrix syntax

.buildkite/webcms.yml
This variable wasn't being propagated down to `build-images.sh` in the `webcms.yml` pipeline.
=> Ensure $WEBCMS_REPO_URL is defined

.buildkite/webcms.yml, ci/util.js
This PR limits Drush to one run per combination of site and language.
=> Limit drush concurrency to 1

.buildkite/webcms.yml, ci/util.js
This PR makes two changes:
1. It corrects the "Task logs" link to point directly to CloudWatch, and
2. It reverts the Buildkite matrix for Drush tasks in order to allow English and Spanish deployments to occur side-by-side.
=> EPAD8-1271: Build improvements

ci/ecs.js
This PR tracks the Drush container status explicitly. We have had some build failures in AWS where Drush runs out of memory, but Buildkite reports a zero exit code: it's possible that ECS has shuffled the containers array in the API return value.
=> EPAD8-1271: Find drush container explicitly

terraform/infrastructure/cron.tf, terraform/infrastructure/parameters.tf, terraform/webcms/README.md, terraform/webcms/shared.tf
This PR creates per-site EventBridge rules in order to support running more than two sites on the same environment. See the comments in the Terraform for more context.
**Deployment notes**: After this is merged, `EPAD8-1271` will need to be merged into `main` first in order to establish the new cron rules, and then we can merge down into `release` and `integration`.
=> EPAD8-1713: Create per-site EventBridge rules

.buildkite/feature.yml
This PR prevents the network and infrastructure plans from seeing the `$WEBCMS_SITE` variable in Buildkite. This was creating multiple concurrency groups for the same shared resource, resulting in Terraform potentially failing due to lock contention.
=> EPAD8-1271: Fix plan concurrency

README.md
This PR updates the readme to point to https://epa.ddev.site instead of https://epa-dev.ddev.site. My IDE also removed trailing spaces.
=> Update readme to correct local site

.buildkite/feature.yml, .buildkite/webcms.yml, services/drupal/Dockerfile
This PR fixes image builds failing due to a missing `-lcrypto` dependency, causing these build errors:
```
checking whether compiling and linking against OpenSSL works... no
checking for CRYPTO_new_ex_data in -lcrypto... no
configure: error: OpenSSL libraries required
```
In addition, to avoid out-of-memory conditions in our default agent pool, this PR moves Docker image builds to the more powerful docker-builders pool.
=> Fix missing OpenSSL dependency in image builds

services/drupal/Dockerfile
This PR works around breaking changes that appear to have been introduced by awslabs/aws-elasticache-cluster-client-libmemcached#19, which cause our usage of memcached to segfault. We roll back to a known-good checkout until we can fix the upstream issue in libmemcached.
=> Pin to known-good libmemcached checkout

services/drupal/Dockerfile, terraform/webcms/drush.tf
In order to reduce costs incurred by AWS Config, this PR moves Drush cron invocations to a persistent ECS service. This change effectively eliminates new Config records created by the repeated EventBridge invocations.
This has been tested on an environment already, so it appears that the new Docker entrypoint and default command do not have any adverse impacts.
=> EPAD8-1721: Move cron to persistent Drush container

.buildkite/pipeline.yml
This PR adds Buildkite logic to deploy to the following new environments: `live` and `uswds`.
=> EPAD8-1176: Allow building to new environments

.buildkite/feature.yml, .buildkite/webcms.yml
Per GoogleContainerTools/kaniko#2227, new versions of Kaniko fail immediately upon detecting a multi-stage build with `COPY` layer caching. I haven't fully dug into the reasons why, but it appears that there are some fairly severe bugs lurking there, so we're better off removing the option.
=> EPAD8-1854: Disable COPY caching for Kaniko

services/drupal/web/themes/epa_theme/source/_patterns/02-base/02-html-elements/00-universal/_universal.scss, services/drupal/web/themes/epa_theme/source/_patterns/03-uswds/_index.scss, services/drupal/web/themes/epa_theme/source/_patterns/03-uswds/nav/_nav.scss, services/drupal/web/themes/epa_theme/source/_patterns/utility-classes/_accessibility.scss
This PR adds overrides for transition and animation when the browser is set to `prefers-reduced-motion`.
There appears to be only one `animation`, being set by a USWDS pattern on the nav. `.usa-nav.is-visible`. We set the media query for animation to be really quick, it's like there is no animation. We don't set animation to none because we need the final translate added to the nav element as set by the animation. 
There are multiple instances of `transition` being set on elements. While transitions can be accessible, it's safer to turn them off entirely. In the same way we handle animations, we transition so quick, it's like there was no transition at all. There are a handful of transitions being set on elements and in components. I could break the transition override out into the …
=> EPAD8-1648: Prefers reduced motion

services/drupal/web/themes/epa_theme/source/_patterns/utility-classes/_full-width.scss
when JS is diasbled, the hero slideshow is rendering incorrectly. this is because the scrollbar width is set to `0` instead of `0px`, which is required for any length properties using calc. there's a style lint exception added to bypass the "0 has no unit" rule since we need to have a unit.
notes on calc rule: [Mozilla Dev Docs for Calc](https://developer.mozilla.org/en-US/docs/Web/CSS/calc)
> For lengths, you can't use 0 to mean 0px (or another length unit); instead, you must use the version with the unit: margin-top: calc(0px + 20px); is valid, while margin-top: calc(0 + 20px); is invalid.
=> [EPAD8-1857] - Hero Slideshow isn’t full-width when JS is disabled

services/drupal/web/themes/epa_theme/source/_patterns/05-components/hero-slideshow/_hero-slideshow.scss
this PR sets the first slide in the slider to be stacked on top when javascript is turned off as it is currently showing the last slide due to the stacking order set by grid. 
this PR sets the first slide's z index to be on top. while that should be enough, to be sure, the other slides are set to not be displayed.
=> Epad8 1873 no js slider first

terraform/webcms/shared.tf
This PR corrects a typo in the parameter declaration in the WebCMS Terraform module.
=> EPAD8-1900: Use correct parameter name

terraform/infrastructure/drupal_iam_exec.tf
This PR addresses a missing `GetSecretValue` permission needed to pull the new basic auth secret.
=> EPAD8-1900: Grant access to the basic auth secret

terraform/webcms/drupal.tf, terraform/webcms/shared.tf
This PR moves the WEBCMS_BASIC_AUTH environment variable into the nginx container instead of Drupal.
=> EPAD8-1900: Inject secret into nginx

services/drupal/web/themes/epa_theme/epa_theme.libraries.yml, services/drupal/web/themes/epa_theme/gulpfile.js
This PR fixes the font path error in the new component stylesheets.
Currently the font paths are incorrect in the new split stylesheets because the stylesheets are nested in individual component folders. The font path is set in `config.design-tokens.yml` to go only up one folder `line 9: font-path: '../fonts'`, causing the fonts in nested folders to error.
The fonts are generally loading correctly due to the core stylesheet being in the right location for the fonts to be linked properly. However, we should still fix the loading error! 
We do this by editing the gulpfile. When buildSass runs, we check to see if our directory name is anything other than '.' (our base). If it does have a directory name, we replace it with '.'
Additionally, some of the split stylesheets were named "index" …
=> EPAD8-1899 - Fix Font Path in New Split Stylesheets

services/drupal/web/themes/epa_claro/css/styles.css, services/drupal/web/themes/epa_claro/epa_claro.info.yml
This PR wraps the definition text when adding a dictionary term.
The issue is caused by CSS reset that is occuring in editor.css
`/modules/contrib/ckeditor/vendor/skins/moono-lisa/editor.css`
`.cke_reset_all * {white-space: nowrap;}`
It's setting all content in the CKE editor to have no white space wrapping. Thus when there is really long text, it'll stretch the parent box causing the issue reported.
This PR fixes the problem for just the definition on a dictionary term, but this could be happening on other items. I clicked into numerous different options set in the editor and did not find any other examples. That doesn't mean it's not happening though!
=> Epad8 1904 definitions in claro try 2

services/drupal/web/themes/epa_claro/css/styles.css
this issue is caused by the jquery ui theme.css setting any links under .ui-widget-content to be #333 and the layout builder .css setting the background color on list items links to have a background color of #444.
this PR sets the link color to white and lightly updates the styling of the list items.
#fff / #444 passes color contrast requirements.
=> EPAD8-1903 EPA Claro color contrast improvement for layout builder

services/drupal/web/themes/epa_theme/js/src/protected-links.es6.js
this PR changes the label that appears on external links that feature the "lock icon" from `Link to protected area` to `Exit to EPA’s internal site`. Confirmed it's rendering on pattern lab.
=> EPAD8-1840 Change Internal Link Text

services/drupal/web/modules/custom/epa_workflow/css/revision-list.css
the PR highlights the latest revision in the revisions tab with a light yellow background color. 
the selector is set to work on `.revision-latest:not(.revision-current)`. 
I added the content in the CSS file for the EPA Workflow module. I tested to confirm the background color is rendering in Claro and Seven theme.
=> EPAD8-1805 Latest Revision Background Color

terraform/webcms/drush.tf, terraform/webcms/variables.tf
Making two changes that allow us to set the number of drush tasks to 0 if desired.  Adds a default value of "1" to the drush tasks variable to make the variable optional
=> Allowfor0drushpods

services/drupal/web/themes/epa_seven/css/base/elements.css
This PR adds a little bit of CSS to update the styling for the Media Grid view in Seven theme. 
This also lightly styles the required text, which I believe will also happen in EPA-1946. Will update that PR as well.
=> EPAD8-1612 Media Grid Library Checkboxes are Cut Off

services/drupal/web/themes/epa_theme/source/_patterns/05-components/hero-slideshow/hero-slideshow.scss, services/drupal/web/themes/epa_theme/source/_patterns/05-components/image-gallery/image-gallery.scss, services/drupal/web/themes/epa_theme/source/_patterns/tiny-slider.scss
This update removes the depreciation warning from tiny-slide.scss. The tiny-slider SASS has been moved to the local template and then updated to resolve the depreciation warnings. 
There are two components which used Tiny Slider, The Homepage Hero Slideshow and the generic Image Gallery. 
I've confirmed they are working as expected with this update. 
Test:
https://integration.epa.byf1.dev/education-0
JIRA:
https://forumone.atlassian.net/browse/EPAD8-2020
=> EPAD8-2020 Replace depreciated math in tiny-slider

services/drupal/config/sync/editoria11y.settings.yml, services/drupal/config/sync/user.role.beta_tester.yml, services/drupal/config/sync/user.role.system_webmaster.yml
This PR:
- ignored the add to cal module and any children links
- removes the editorially module from role "webmaster"
- adds the editoria11y module to the role "beta tester" with 3 of 5 permissions.
=> Epad8 2024 editorally tweaks

services/drupal/web/themes/epa_theme/source/_patterns/00-config/01-mixins/_mixins.aspect-ratio.scss, services/drupal/web/themes/epa_theme/source/_patterns/00-config/01-mixins/_mixins.grids.scss
Per a discussion yesterday we have decided to leave the Tiny Slider style updates as is, which continues to prevent the division depreciation warnings.  This update targets the use of `/` for division and replaces it with `math.div` in SASS partials. The following files were updated:
- _mixins.aspect-ratio.scss
- _mixins.grid.scss
I have browsed the website in general to ensure the grid was not effected negatively and have verified that the aspect-ratio works as expected. 
This is a Fast Track update and the PR has been made into `main`. 
View:
https://integration.epa.byf1.dev/
https://integration.epa.byf1.dev/node/280300/latest (Video embed uses the updated aspect-ratio updates)
JIRA:
https://forumone.atlassian.net/browse/EPAD8-2020
=> EPAD8-2020: Convert division / to math.div in all sass partials

services/drupal/web/themes/epa_theme/source/core.scss, services/drupal/web/themes/epa_theme/source/styles.scss, services/drupal/web/themes/epa_theme/source/wysiwyg.scss
This PR brings the styling for 'uswds intro' into all stylesheets that import uswds. (styles.scss, core.scss, wysiwyg.scss).
=> EPAD8-2011 add usa intro styling into stylesheets

services/drupal/web/themes/epa_theme/templates/paragraph/paragraph--card.html.twig
Cards in card groups work with the following options:
- Images will now display indent and extent in 50/50 and 33/33/33 views
- Header will now display first or below image on 33/33/33 view
Notes:
This branch is based from `EPAD8-1882-card-option-updates`
View:
https://integration.epa.byf1.dev/education/card-groups
JIRA:
https://forumone.atlassian.net/browse/EPAD8-1882
=> EPAD8-1882:FED work for  Media First and Inset options

services/drupal/web/themes/epa_theme/source/_patterns/07-pages/detail-pages/03-page-with-wide-template.twig, services/drupal/web/themes/epa_theme/source/_patterns/07-pages/detail-pages/regulation.twig, services/drupal/web/themes/epa_theme/templates/content/node--regulation--full.html.twig
This update converts the "On this page:" note to be in an 'H2' element with an 'H4' class for the Regulation content type in Drupal and Pattern Lab. 
View:
https://integration.epa.byf1.dev/education/regulation-page
JIRA:
https://forumone.atlassian.net/browse/EPAD8-2003
=> EPAD9-2003: Convert On This Page to h2 element

services/drupal/web/themes/epa_theme/source/_patterns/05-components/box/box--blog/_box--blog.scss, services/drupal/web/themes/epa_theme/source/_patterns/05-components/box/box--blog/box--blog.md
This PR changes the Pattern Lab name of `Blog Box` to `Perspectives Box`, but keeps all the classes the same. 
Updates the footer link to be blue like default links and confirmed the blue text / light green bg passes accessibility standards.
=> EPAD8-1935: change box blog to box perspectives, footer link styling

services/drupal/web/themes/epa_theme/js/src/modules/_back-to-top.es6.js
This PR resets the change in back-to-top.js to use query selector instead of once. The once setting change was preventing the javascript from applying the correct classes to the back to top button.
=> EPAD8-2174 revert back to top js from once to query selector

services/drupal/web/themes/epa_theme/js/src/external-links.es6.js, services/drupal/web/themes/epa_theme/source/_patterns/05-components/external-link/external-link.twig
This PR updates the allowed list with the newly requested URLs, adds linkedin to the social media allowed list, and removes Urban Water Partners from the allowed list. This PR also updates the list in Pattern Lab.
=> EPAD8-2156 update allowed links

services/drupal/config/sync/field.storage.node.field_language.yml, services/drupal/web/themes/epa_theme/includes/facets.inc, services/drupal/web/themes/epa_theme/source/_patterns/03-uswds/collection/_collection-item.twig, services/drupal/web/themes/epa_theme/source/_patterns/03-uswds/collection/collection-item.md, services/drupal/web/themes/epa_theme/source/_patterns/05-components/facet/_facet.scss, services/drupal/web/themes/epa_theme/templates/content/node--event--teaser.html.twig, services/drupal/web/themes/epa_theme/templates/content/node--faq--teaser.html.twig, services/drupal/web/themes/epa_theme/templates/content/node--news-release--teaser.html.twig, services/drupal/web/themes/epa_theme/templates/content/node--perspective--teaser.html.twig, services/drupal/web/themes/epa_theme/templates/content/node--public-notice--teaser.html.twig, services/drupal/web/themes/epa_theme/templates/content/node--regulation--teaser.html.twig, services/drupal/web/themes/epa_theme/templates/content/node--speeches--teaser.html.twig, services/drupal/web/themes/epa_theme/templates/content/node--teaser.html.twig, services/drupal/web/themes/epa_theme/templates/content/node--web-area--teaser.html.twig, services/drupal/web/themes/epa_theme/templates/facets/facets-item-list.html.twig, services/drupal/web/themes/epa_theme/templates/facets/facets-result-item.html.twig
This PR adds the lang attribute to facets and teasers. 
The facet language has been update in config to have the appropriate language name / value key pair. 
On the teasers, the collection list item has been updated to accept attributes, and the language attribute is being passed through all teaser templates.
=> Epad8 2189 lang attributes facets

.buildkite/feature.yml
A quick fix to prep for cleaning up stale images in ECR: this corrects an oversight where only the fpm-metrics container is pushed during feature branch builds.
=> Don't push fpm-metrics images on feature builds

services/drupal/default.conf
This PR tells nginx to not output any version information in responses, both ignoring its own output (the `server_tokens` directive) and PHP's (the `fastcgi_ignore_header` directive).
=> EPAD8-2241: Ignore version tokens in responses

terraform/webcms/README.md, terraform/webcms/shared.tf
This is blocking builds to main, as these parameters no longer exist.
=> Fix loading unused cron parameters

terraform/webcms/drupal_schedule.tf, terraform/webcms/variables.tf
This PR implements a scheduled scaling policy in order to elevate the minimum task count before US Eastern working hours, since the majority of the site's content editors are in this time zone. In the evening, the minimum task count is lowered in order to allow ECS to gradually scale in overnight.
=> EPAD8-2272: Implement schedule scaling

services/drupal/web/themes/epa_theme/js/src/epa-alerts.es6.js
This PR fixes a bug where blank response data was overwriting alert data so that alerts wouldn't show. It adds a check in to make sure there is data before updating HTML.
=> EPAD8-2321 Show Alerts 

services/drupal/web/themes/epa_theme/js/src/private-sitewide-alert.es6.js
This PR fixes the issue when there is a private file on a page the 508 compliance box won't show up.
The private file alert banner was being added to the body using the document, rather than the context, which was causing the dynamically loading compliance box to stay hidden. Once updated, there was a console error, so I refactored the code slightly to use once so that it would only fire once.
=> Epad8 2334 private 508 bug

services/drupal/Dockerfile
This PR bumps the New Relic agent version to the latest release.
=> EPAD8-2071: Bump NR agent version

services/drupal/Dockerfile
This automatically bumps system package versions during builds, in order to capture important updates to libraries like OpenSSL.
=> EPAD8-2353: Add `apk upgrade` to build

services/drupal/web/themes/epa_theme/source/_patterns/03-uswds/summary-box/_summary-box.scss
this PR styles the default summary box text and links when they're on dark backgrounds so that they meet accessibility standards.
=> EPAD8-2114 dark background styles for summary box

services/drupal/web/themes/epa_theme/source/_patterns/03-uswds/alert/_alert.scss, services/drupal/web/themes/epa_theme/source/_patterns/03-uswds/site-alert/_site-alert.scss, services/drupal/web/themes/epa_theme/source/_patterns/05-components/site-alert/site-alert--private/_site-alert--private.scss
This PR fixes a bug where the site alerts weren't filling up the banner space fully. It also adds a narrow restriction to the private files alert so that it matches the figma file.
=> Epad8 1332 alert sizing

terraform/infrastructure/README.md, terraform/infrastructure/ecr.tf, terraform/infrastructure/logging.tf, terraform/infrastructure/parameters.tf, terraform/webcms/README.md, terraform/webcms/drupal.tf, terraform/webcms/shared.tf
This PR removes the CloudWatch agent used to gather metrics published via the now-inactive `epa_metrics` module.
=> EPAD8-2384: Remove CloudWatch agent

.buildkite/feature.yml, .buildkite/webcms.yml, services/metrics/Dockerfile
This PR switches out the Alpine-based metrics container with Debian in order to download the latest AWS CLI.
Note that the commits mentioning Kaniko issues are due to issues within our Buildkite environment, not others, so there are no issues to notify upstream about.
=> EPAD8-2370: Switch metrics container to Debian to bring in latest AWS CLI

terraform/infrastructure/ecr.tf
This PR adds two lifecycle rules to each major ECR repository:
1. Any untagged image is expired within 24 hours, and
2. At most 10 tagged images are retained.
=> EPAD8-2216: Add ECR lifecycle policies

.buildkite/webcms.yml
This PR allows long-running ECS tasks by changing how the Drush CI script loads authentication credentials. It's a relatively small change that is easy to test: if Drush is still able to be dispatched, then this change will work for tasks of any length.
=> Support long-running Drush tasks

services/drupal/web/themes/epa_theme/source/_patterns/03-uswds/summary-box/_summary-box.scss, services/drupal/web/themes/epa_theme/source/_patterns/05-components/box/_box.scss, services/drupal/web/themes/epa_theme/source/_patterns/05-components/definition/_definition.scss
this PR addresses oddities with the definitions popup in different parent containers.
it:
- removes the overflow auto on boxes so that definitions don't scroll within the box. Adds clearfix items to account for potential float issues
- adds a min width to the definition so that when the parent is really small, like in a narrow table, the definition tooltip is has enough reading room.
=> EPAD8-2184 definitions cut off

services/drupal/web/themes/epa_theme/source/_patterns/05-components/box/_box.scss
makes h2's that are titles on boxes that are not bordered 28px
=> EPAD8-2288 h2 box title not bordered is smaller

services/drupal/Dockerfile, terraform/webcms/drush.tf
This PR modifies the Drush container in order to run as a non-root user. The new `USER` directive at the bottom of the Dockerfile is what accomplishes this; it embeds metadata that scanners can pick up:
```
$ docker build services/drupal --target drush --tag epa-drush
[snip]
$ docker inspect epa-drush | jq '.[0].Config.User'
"www-data"
```
In order to accommodate this change, we had to replace the `crond`-based scheduling. Alpine Linux (our base distribution) uses Busybox cron, which opens with this comment (see [crond.c](https://git.busybox.net/busybox/tree/miscutils/crond.c?h=1_36_1#n3)):
```c
/*
* run as root, but NOT setuid root
*
```
I experimented with trying a few workarounds, but couldn't get anywhere. The container itself doesn't really have any sophisticated scheduling needs: …
=> EPAD8-2412: Make Drush run as a non-root user

services/drupal/web/themes/epa_theme/source/_patterns/05-components/hero-slideshow/_hero-slideshow.scss
uses css to make it so that links in hidden homepage slides cannot be tabbed to
=> Epad8 2250 hidden elements in homepage banners cannot be focused 

services/drupal/Dockerfile
This PR changes the PHP-FPM process pool to static instead of dynamic. We use a fixed pool of 10 processes, and restart each process after it handles 5,000 requests in order to avoid any long-term instability.
=> EPAD8-2475: Change FPM pool to static

services/drupal/Dockerfile
This PR adds the `PHP_ERROR_REPORTING` build arg to this project's Dockerfile. The default in the build is a production-ready one that ignores certain development-only messages.
Our own builds have not been adjusted to return to `E_ALL` reporting, but we can change that at any time.
=> EPAD8-2521: Allow changing error_reporting

services/drupal/default.conf
This PR updates the nginx configuration to allow the `/rss` and `/rss/` subpaths to be subject to normal processing, before the HTTP 410 Gone blocks apply.
=> EPAD8-2513: Allow RSS feeds

services/drupal/config/sync/views.view.group_members.yml, services/drupal/web/themes/epa_claro/css/styles.css
Adjusted two files to tighten up the "can publish?" button on the group member dashboard
=> Saving work to fix Can Publish button in group member dashboard

services/drupal/composer.json, services/drupal/composer.lock, services/drupal/composer.patches.json
I removed patch: https://www.drupal.org/files/issues/2020-09-30/3098733-7.patch. The issue the patch fixed (avoiding empty data-* attributes) is likely no longer applicable for version 8.x-2.0-beta24.
=> WEBCMS-53 update Entity Usage module (8.x-2.0-beta12 to 8.x-2.0-beta24)
