USEPA/webcms

infrastructure/terraform/cluster.tf

This PR enables gathering task- and container-level metrics via Container Insights.

Enable container insights

---

services/drupal/web/modules/custom/epa_workflow/epa_workflow.module

Tweak 508 assertion

---

.buildkite/run-drush.sh

As a stopgap before we're able to fully evaluate CodeDeploy, this PR adds some code to the build script to stop all running Drupal tasks in the cluster before running Drush. Since this step occurs after Terraform has updated the task definitions, ECS will start new tasks with the up-to-date code. This prevents cache corruption from old tasks while Drush performs updates or cache rebuilds.

EPAD8-892: Stop tasks before Drush runs

---

infrastructure/terraform/cloudwatch.tf

This PR is the first of several capturing the dashboards we have built into Terraform.

EPAD8-777: Add overview dashboard

---

services/drupal/config/sync/migrate_plus.migration.upgrade_d7_node_page_sixpack.yml
services/drupal/config/sync/migrate_plus.migration.upgrade_d7_node_revision_page_sixpack.yml
services/drupal/web/modules/custom/epa_migrations/config/install/migrate_plus.migration.upgrade_d7_node_page_sixpack.yml
services/drupal/web/modules/custom/epa_migrations/config/install/migrate_plus.migration.upgrade_d7_node_revision_page_sixpack.yml
services/drupal/web/modules/custom/epa_migrations/src/Plugin/migrate/source/EpaSixpackNode.php
services/drupal/web/modules/custom/epa_migrations/src/Plugin/migrate/source/EpaSixpackNodeRevision.php

https://forumone.atlassian.net/browse/EPAD8-941

[EPAD8-941] Create migrations for pages with six_pack layout

---

infrastructure/terraform/s3.tf

This PR fixes an issue in the previous PR's bucket policy.

EPAD8-998: Fix typo in principal ARN

---

services/drupal/composer.json
services/drupal/composer.lock
services/drupal/composer.patches.json
services/drupal/patches/webform-migrate-d7-yaml-encoding.patch

No more YAML parse errors reported during `upgrade_d7_webform` but the migration always fails with the following:
```
[error]  Error: Call to a member function getRuntimeContexts() on null in Drupal\content_moderation_notifications\Notification->sendNotification() (line 186 of /var/www/html/web/modules/contrib/content_moderation_notifications/src/Notification.php) #0 /var/www/html/web/modules/contrib/content_moderation_notifications/src/Notification.php(100): Drupal\content_moderation_notifications\Notification->sendNotification(Object(Drupal\node\Entity\Node), Array)
#1 /var/www/html/web/modules/custom/epa_workflow/src/EPANotification.php(65): Drupal\content_moderation_notifications\Notification->processEntity(Object(Drupal\node\Entity\Node))
#2 …
```

EPAD8-929 Fix YAML encoding and other issues in webform migrate

---

infrastructure/terraform/cluster.tf

This PR uses the random provider's [keepers](https://registry.terraform.io/providers/hashicorp/random/latest/docs#resource-keepers) to force the creation of new ECS capacity providers with different names. Hopefully, this will result in fewer complaints from Terraform, should we change the capacity provider settings.

Use keepers for capacity providers

---

services/drupal/web/themes/epa_theme/source/_patterns/05-components/box/box.twig
services/drupal/web/themes/epa_theme/source/_patterns/05-components/box/box.yml

added link to our box standard documentation

add documentation

---

services/drupal/web/themes/epa_theme/source/_patterns/01-global/00-colors/color.twig
services/drupal/web/themes/epa_theme/source/_patterns/01-global/00-colors/color.yml

@dcmouyard  I added a link to USWD color page. I added it just after the title because I thought it would get lost at the bottom of the page.

add link to USWD color page

---

services/drupal/web/themes/epa_theme/source/_patterns/05-components/external-link/external-link.twig
services/drupal/web/themes/epa_theme/source/_patterns/05-components/external-link/external-link.yml

@dcmouyard I added a link to the External Site Link Procedure -ce

added link to External Site Links Procedure

---

services/drupal/web/themes/epa_theme/source/_patterns/05-components/new/new.twig
services/drupal/web/themes/epa_theme/source/_patterns/05-components/new/new.yml

@dcmouyard I added a link to our Web Standard: New! Icon -ce

added link to New Icon standard

---

README.md
services/drupal/web/modules/custom/epa_migrations/src/EpaBoxWrapperTrait.php
services/drupal/web/modules/custom/epa_migrations/src/EpaCoreHtmlPaneToParagraph.php
services/drupal/web/modules/custom/epa_migrations/src/EpaCoreListPaneToParagraph.php
services/drupal/web/modules/custom/epa_migrations/src/EpaMediaWysiwygTransformTrait.php

https://forumone.atlassian.net/browse/EPAD8-1015

[EPAD8-1015] [Migration] Link on Box Paragraphs

---

services/drupal/web/akamai-test-object.html

This file is checked by Akamai every five minutes to ensure that www.epa.gov is available. It's a simple heartbeat; we're working to have more added.

Adding the akamai-test-object.html to the web root

---

services/drupal/config/sync/migrate_plus.migration.upgrade_d7_file.yml
services/drupal/config/sync/migrate_plus.migration.upgrade_d7_file_entity_audio.yml
services/drupal/config/sync/migrate_plus.migration.upgrade_d7_file_entity_document.yml
services/drupal/config/sync/migrate_plus.migration.upgrade_d7_file_entity_image.yml
services/drupal/config/sync/migrate_plus.migration.upgrade_d7_file_entity_other.yml
services/drupal/config/sync/migrate_plus.migration.upgrade_d7_file_entity_video.yml
services/drupal/web/modules/custom/epa_migrations/config/install/migrate_plus.migration.upgrade_d7_file.yml
services/drupal/web/modules/custom/epa_migrations/config/install/migrate_plus.migration.upgrade_d7_file_entity_audio.yml
services/drupal/web/modules/custom/epa_migrations/config/install/migrate_plus.migration.upgrade_d7_file_entity_document.yml
services/drupal/web/modules/custom/epa_migrations/config/install/migrate_plus.migration.upgrade_d7_file_entity_image.yml
services/drupal/web/modules/custom/epa_migrations/config/install/migrate_plus.migration.upgrade_d7_file_entity_other.yml
services/drupal/web/modules/custom/epa_migrations/config/install/migrate_plus.migration.upgrade_d7_file_entity_video.yml
services/drupal/web/modules/custom/epa_migrations/src/Plugin/migrate/source/EpaFile.php
services/drupal/web/modules/custom/epa_migrations/src/Plugin/migrate/source/EpaFileEntityItem.php

Timestamps allowed some duplicates to be missed.
https://forumone.atlassian.net/browse/EPAD8-1022

[EPAD8-1022] Use fid for file migration high water mark

---

services/drupal/scripts/ecs/drush-migrate.sh

Or instead of this I can just run the upgrade alone in a task...

Update banner slide migration in the script

---

infrastructure/terraform/automation.tf

for https://forumone.atlassian.net/browse/EPAD8-1088

Adds the D8Load-Database automation needed to populate QA

---

services/drupal/web/themes/epa_theme/source/_patterns/05-components/box/box--aligned-right-stacked/box--aligned-right-stacked.md
services/drupal/web/themes/epa_theme/source/_patterns/05-components/box/box--aligned-right-stacked/box--aligned-right-stacked.twig
services/drupal/web/themes/epa_theme/source/_patterns/05-components/box/box--aligned-right-stacked/box--aligned-right-stacked.yml
services/drupal/web/themes/epa_theme/source/_patterns/05-components/box/box.twig

https://forumone.atlassian.net/browse/EPAD8-1052
Wondering if this work is on the right track.

Adding stacked boxes

---

.buildkite/pipeline.yml

Update Buildkite to deploy `D9-migration-test` to Stage.

[EPAD8] Deploy D9-migration-test to Stage

---

services/drupal/web/themes/epa_theme/gulpfile.js

Also runs Prettier over the gulp file, which fixes a few minor code formatting things.

[EPAD8-1257] Minify CSS as part of the gulp build task

---

services/drupal/config/spanish/system.site.yml
services/drupal/config/sync/system.site.yml

https://forumone.atlassian.net/browse/EPAD8-1358

Epad8 1358 noreply email

---

services/drupal/config/sync/image.style.huge_gallery.yml
services/drupal/config/sync/image.style.large_gallery.yml
services/drupal/config/sync/responsive_image.styles.responsive_gallery_image.yml
services/drupal/web/themes/epa_theme/source/_patterns/05-components/figure/figure--gallery/_figure--gallery.scss
services/drupal/web/themes/epa_theme/source/_patterns/05-components/image-gallery/_image-gallery.scss
services/drupal/web/themes/epa_theme/source/_patterns/05-components/image-gallery/image-gallery.yml
services/drupal/web/themes/epa_theme/templates/media/media--image--gallery.html.twig

Have the slides use the medium (640x360px) image instead of the small, update styles accordingly

Epad8 1352 slideshows larger

---

services/drupal/web/themes/epa_theme/source/_patterns/07-pages/detail-pages/public-notice.twig
services/drupal/web/themes/epa_theme/templates/field/field--node--body--public-notice--full.html.twig
services/drupal/web/themes/epa_theme/templates/field/field--node--field-docket-numbers--public-notice--full.html.twig
services/drupal/web/themes/epa_theme/templates/field/field--node--field-federal-register-citations--public-notice--full.html.twig
services/drupal/web/themes/epa_theme/templates/field/field--node--field-related-documents--public-notice--full.html.twig

Removed the custom class for the h2 elements on public notice pages

EPAD8-1359 remove unique header styles on public notices

---

services/drupal/redirect_301.map

We want to capture www.epa.gov/orcdizux/datafiles/batchfiles/ and send them to www3.epa.gov/otaq/datafiles/batchfiles/

Fixed orcdizux

---

services/drupal/web/modules/custom/epa_media/epa_media.install

Note: I haven't tested this against a large or prod-like database, but wanted to get this in front of some eyes sooner rather than later. If there's ways I can optimize the queries please let me know.

[EPAD8-1349] Adding hook_update_N() to change "Document" media items that use json or xml files to become "Other" media bundle

---

services/drupal/redirect_301.map

Remove climate-change-science redirect from nginx

---

terraform/webcms/drupal.tf

Specify the max_capacity explicitly

Troubleshoot scheduled_action

---

.gitlab-ci.yml

Also changing to "rules" instead of "only"

Changing to "live" branch

---

.gitlab-ci.yml

Need to make sure CI_COMMIT_TAG isn't empty, not that it simply exists

CI_COMMIT_TAG logic incorrect

---

services/drupal/composer.lock
services/drupal/composer.patches.json

Removing patch as it has now been fixed in latest release also.

[EPAD8-1422] Updating webform module to 6.0.5

---

services/drupal/web/themes/epa_theme/source/_patterns/07-pages/web-area-homepages/microsite.twig

Fixed typo in first banner button

---

services/drupal/composer.patches.json
services/drupal/config/sync/core.entity_view_display.node.news_release.default.yml
services/drupal/web/modules/custom/epa_core/config/schema/epa_core.schema.yml
services/drupal/web/modules/custom/epa_core/epa_core.module
services/drupal/web/modules/custom/epa_core/epa_core.theme.inc
services/drupal/web/modules/custom/epa_core/src/Plugin/Field/FieldFormatter/HierarchicalFacetFormatter.php
services/drupal/web/modules/custom/epa_core/templates/hierarchical-term-facet-formatter.html.twig
services/drupal/web/themes/epa_theme/epa_theme.theme
services/drupal/web/themes/epa_theme/includes/node.inc
services/drupal/web/themes/epa_theme/source/_patterns/05-components/field/_field.scss
services/drupal/web/themes/epa_theme/source/_patterns/05-components/hublinks/_hublinks.scss
services/drupal/web/themes/epa_theme/source/_patterns/05-components/hublinks/hublinks.md
services/drupal/web/themes/epa_theme/source/_patterns/05-components/hublinks/hublinks.twig
services/drupal/web/themes/epa_theme/source/_patterns/05-components/hublinks/hublinks.yml
services/drupal/web/themes/epa_theme/templates/content/node--news-release--full.html.twig
services/drupal/web/themes/epa_theme/templates/field/field--field-hublinks.html.twig
services/drupal/web/themes/epa_theme/templates/field/field--field-press-office.html.twig

JIRA: https://forumone.atlassian.net/browse/EPAD8-1469

EPAD8-1469 news releases header text

---

services/drupal/config/sync/field.field.media.other.field_media_file_1.yml

Done locally, but I think I could have just edited the configuration file directly. The uuid did not change.

Adding .xlsb file extension to 'other' bundle

---

services/drupal/web/modules/custom/epa_workflow/src/EPAScheduledPublishCron.php
services/drupal/web/modules/custom/epa_workflow/src/EPAUnpublished.php

Also ensure we only process ripe transitions

EPAD8-1524 Sunset date: ensure additional transitions are cleared out on unpublishing

---

services/drupal/web/themes/epa_theme/source/_patterns/03-uswds/hero/_hero.scss

JIRA: https://forumone.atlassian.net/browse/EPAD8-1535

[EPAD8-1535] remove background image on .usa-hero

---

services/drupal/web/themes/epa_theme/source/_patterns/03-uswds/alert/alert.twig
services/drupal/web/themes/epa_theme/source/_patterns/03-uswds/alert/alert.yml

JIRA: https://forumone.atlassian.net/browse/EPAD8-1405

[EPAD8-1405] allow heading changes to alert, default to h2

---

services/drupal/composer.patches.json

EPAD8-1067 provide accurate ES result counts when there are over 10k 

---

terraform/webcms/target_group.tf

Running into character limit for the name of the target group, removing prefix and suffix to move forward

Removing "webcms-" prefix and "-drupal" suffix

---

terraform/webcms/shared.tf

VPC ID needed for ALB target group setup

Adding VPC ID parameter

---

services/drupal/web/themes/epa_theme/source/_patterns/00-config/01-mixins/_mixins.button.scss
services/drupal/web/themes/epa_theme/source/_patterns/03-uswds/summary-box/_summary-box.scss
services/drupal/web/themes/epa_theme/source/_patterns/05-components/form-item/form-item--checkboxes/_form-item--checkboxes.scss
services/drupal/web/themes/epa_theme/source/_patterns/05-components/form-item/form-item--radios/_form-item--radios.scss

JIRA: https://forumone.atlassian.net/browse/EPAD8-1556

[EPAD8-1556] remove component imports in favor of global

---

services/drupal/patches/diff-patch-revision-language-to-match-3252521-2899719-3252540-2.patch
services/drupal/web/modules/custom/epa_workflow/css/revision-list.css
services/drupal/web/modules/custom/epa_workflow/epa_workflow.module

JIRA: https://forumone.atlassian.net/browse/EPAD8-1558

EPAD8-1558 additional revision listing updates

---

services/drupal/web/themes/epa_theme/source/_data/menu--main.yml
services/drupal/web/themes/epa_theme/source/_meta/_foot.twig
services/drupal/web/themes/epa_theme/source/_meta/_head.twig
services/drupal/web/themes/epa_theme/source/_patterns/07-pages/standalone-template.md
services/drupal/web/themes/epa_theme/source/_patterns/07-pages/standalone-template.twig
services/drupal/web/themes/epa_theme/source/_patterns/07-pages/standalone-template.yml
services/drupal/web/themes/epa_theme/templates/layout/html.html.twig

JIRA: https://forumone.atlassian.net/browse/EPAD8-1560

[EPAD8-1560] add standalone template

---

services/drupal/web/themes/epa_theme/source/_patterns/03-uswds/button/_button.scss
services/drupal/web/themes/epa_theme/source/_patterns/03-uswds/button/button--accent-cool/_button--accent-cool.scss
services/drupal/web/themes/epa_theme/source/_patterns/03-uswds/button/button--inverse/_button--inverse.scss
services/drupal/web/themes/epa_theme/source/_patterns/03-uswds/button/button--outline/_button--outline.scss
services/drupal/web/themes/epa_theme/source/_patterns/03-uswds/button/button--unstyled/_button--unstyled.scss

JIRA: https://forumone.atlassian.net/browse/EPAD8-1563
* clear cache
* buttons do not use inaccessible colors on focus

[EPAD8-1563] override focus styles on usa-button

---

terraform/infrastructure/load_balancer.tf
terraform/infrastructure/traefik_service.tf

Also removes the old Traefik connectors

Adding ALB->NLB connectors

---

services/drupal/web/themes/epa_theme/source/_patterns/03-uswds/modal/_modal.scss
services/drupal/web/themes/epa_theme/source/_patterns/03-uswds/modal/modal.md
services/drupal/web/themes/epa_theme/source/_patterns/03-uswds/modal/modal.twig
services/drupal/web/themes/epa_theme/source/_patterns/03-uswds/modal/modal.yml
services/drupal/web/themes/epa_theme/source/_patterns/03-uswds/modal/modal~force.yml
services/drupal/web/themes/epa_theme/source/_patterns/03-uswds/modal/modal~large.yml

JIRA: https://forumone.atlassian.net/browse/EPAD8-1492

[EPAD8-1492] Add USWDS Modal to components

---

services/drupal/web/themes/epa_theme/package-lock.json
services/drupal/web/themes/epa_theme/package.json

JIRA: https://forumone.atlassian.net/browse/EPAD8-1550
* front-end does not see any changes
* PatternLab compiles same as before
* should only need a cache clear to update styles and JS within Drupal

EPAD8-1550 package updates

---

services/drupal/web/themes/epa_theme/epa_theme.libraries.yml
services/drupal/web/themes/epa_theme/source/_meta/_head.twig
services/drupal/web/themes/epa_theme/source/_patterns/00-config/config.design-tokens.yml
services/drupal/web/themes/epa_theme/templates/layout/html.html.twig

JIRA: https://forumone.atlassian.net/browse/EPAD8-1470

[EPAD8-1470] add Noto fonts and apply to font stack

---

services/drupal/web/themes/epa_theme/js/src/definition.es6.js

JIRA: https://forumone.atlassian.net/browse/EPAD8-1577

[EPAD8-1577] fix aria-describedby attribute

---

services/drupal/web/themes/epa_theme/source/_data/menu--main.yml
services/drupal/web/themes/epa_theme/source/_patterns/05-components/menu/menu--main/_menu--main.scss
services/drupal/web/themes/epa_theme/source/_patterns/05-components/menu/menu--main/menu--main.twig

JIRA: https://forumone.atlassian.net/browse/EPAD8-1607
* cache clear
* menu dropdowns use 3 columns when there are 16 or more elements (15 sub elements and 1 title element)

[EPAD8-1607] add 3rd column in menu if more than 15 elements

---

services/drupal/web/themes/epa_theme/js/src/modules/navigation.js
services/drupal/web/themes/epa_theme/source/_patterns/04-layouts/header/header.twig

JIRA: https://forumone.atlassian.net/browse/EPAD8-1629
Adjusts how the JS is loaded in so we don't double-bind the menu toggle.

EPAD8-1629 mobile menu fix

---

services/drupal/web/themes/epa_theme/source/_patterns/03-uswds/summary-box/_summary-box.scss

JIRA: https://forumone.atlassian.net/browse/EPAD8-1606

[EPAD8-1606] fix overflow on text div

---

services/drupal/composer.lock

EPAD8-1633: Updating drupal/core-recommended and dependancies

---

services/drupal/web/themes/epa_theme/includes/media.inc

JIRA: https://forumone.atlassian.net/browse/EPAD8-1632

[EPAD8-1632] remove incorrect image width

---

services/drupal/web/themes/epa_theme/source/_patterns/07-pages/standalone-template.md
services/drupal/web/themes/epa_theme/source/_patterns/07-pages/standalone-template.twig
services/drupal/web/themes/epa_theme/source/_patterns/07-pages/standalone-template.yml

https://forumone.atlassian.net/browse/EPAD8-1663

Updated content for standard EPA template

---

services/drupal/web/themes/epa_theme/includes/navigation.inc
services/drupal/web/themes/epa_theme/source/_patterns/05-components/button-group/button-group.twig
services/drupal/web/themes/epa_theme/source/_patterns/05-components/menu/menu--main/menu--main.twig
services/drupal/web/themes/epa_theme/source/_patterns/05-components/menu/menu.twig

JIRA: https://forumone.atlassian.net/browse/EPAD8-1647

[EPAD8-1647] add aria-current attribute to current menu item

---

.buildkite/webcms.yml

Looks as a few others were not yet captured.

EPAD8-1271: Propagate more variables

---

services/drupal/composer.lock

| Production Changes      | From    | To      | Compare                                                                 |
|-------------------------|---------|---------|-------------------------------------------------------------------------|
| drupal/core             | 9.3.7   | 9.3.9   | [...](https://github.com/drupal/core/compare/9.3.7...9.3.9)             |
| drupal/core-recommended | 9.3.7   | 9.3.9   | [...](https://github.com/drupal/core-recommended/compare/9.3.7...9.3.9) |
| guzzlehttp/psr7         | 1.8.3   | 1.8.5   | [...](https://github.com/guzzle/psr7/compare/1.8.3...1.8.5)             |
| symfony/filesystem      | v4.4.37 | v4.4.39 | [...](https://github.com/symfony/filesystem/compare/v4.4.37...v4.4.39)  |
| Dev Changes                 | From    | To      | Compare …

EPAD8-1682: Drupal Core Security Update 9.3.9

---

services/drupal/composer.json
services/drupal/composer.lock
services/drupal/config/sync/core.extension.yml
services/drupal/config/sync/linkit.linkit_profile.default.yml
services/drupal/config/sync/linkit_telephone.settings.yml

* Add and enable the [Linkit Telephone](https://www.drupal.org/project/linkit_telephone) module
* Enable the telephone matcher in the default Linkit profile

EPAD8-1667: Linkit Telephone Number Matcher

---

services/drupal/composer.lock
services/drupal/config/sync/core.entity_form_display.paragraph.card_group.default.yml
services/drupal/config/sync/core.entity_view_display.paragraph.card_group.default.yml
services/drupal/config/sync/user.role.system_webmaster.yml

See https://www.drupal.org/sa-core-2022-008.
See https://www.drupal.org/sa-core-2022-009.
| Production Changes            | From  | To     | Compare                                                                        |
|-------------------------------|-------|--------|--------------------------------------------------------------------------------|
| drupal/core                   | 9.3.9 | 9.3.12 | [...](https://github.com/drupal/core/compare/9.3.9...9.3.12)                   |
| drupal/core-composer-scaffold | 9.3.7 | 9.3.12 | [...](https://github.com/drupal/core-composer-scaffold/compare/9.3.7...9.3.12) |
| drupal/core-recommended       | 9.3.9 | 9.3.12 | [...](https://github.com/drupal/core-recommended/compare/9.3.9...9.3.12)       |
| Dev Changes     | From  | To     | Compare …

EPAD8-1715: Core security update - v9.3.12

---

services/drupal/web/themes/epa_theme/source/_patterns/05-components/video/video.md
services/drupal/web/themes/epa_theme/source/_patterns/05-components/video/video.twig
services/drupal/web/themes/epa_theme/source/_patterns/05-components/video/video.yml
services/drupal/web/themes/epa_theme/templates/field/field--media--remote-video.html.twig

JIRA: https://forumone.atlassian.net/browse/EPAD8-1505

[EPAD8-1505] update video to use title in title attribute

---

services/drupal/web/themes/epa_theme/includes/media.inc
services/drupal/web/themes/epa_theme/templates/content-edit/filter-caption.html.twig
services/drupal/web/themes/epa_theme/templates/media/media--remote-video.html.twig

EPAD8-1505 make captions not break rendering of videos.

---

services/drupal/web/themes/epa_theme/templates/misc/status-messages.html.twig

JIRA: https://forumone.atlassian.net/browse/EPAD8-1640

[EPAD8-1640] add role=alert to error messages

---

terraform/infrastructure/parameters.tf

This PR fixes formatting issues in the infrastructure module's parameters.tf file.

Address formatting in parameters.tf

---

services/drupal/web/themes/epa_theme/templates/layout/page--alerts.html.twig

JIRA: https://forumone.atlassian.net/browse/EPAD8-1759

[EPAD8-1759] add l-constrain div to alerts page

---

terraform/infrastructure/rds.tf

This PR changes the Aurora transaction isolation level from the default REPEATABLE-READ to READ-COMMITTED.

EPAD8-1837: Lower transaction isolation level

---

terraform/infrastructure/parameters.tf
terraform/infrastructure/shared.tf
terraform/infrastructure/terraform_db_task.tf

Continuing to remove the database component from terraform

Live remove db

---

.gitlab-ci.yml

Adding us-west-2 infrastructure to the pipeline

Live add us west

---

terraform/infrastructure/cron.tf
terraform/infrastructure/drupal_iam_task.tf
terraform/infrastructure/proxy.tf
terraform/infrastructure/terraform.tf

Updating IAM roles to be region specific

Live us west

---

services/drupal/web/themes/epa_theme/source/_patterns/02-base/02-html-elements/13-headings/headings.twig

[EPAD8-1781] Remove linked headings from Pattern Lab

---

utilities/r/OneEPA_template.R

OK to leave to the next sprint.

Epad8 1879 update r template

---

services/drupal/web/themes/epa_theme/source/_patterns/03-uswds/site-alert/_site-alert.scss

This PR fixes two Stylelint errors. Without this fix, we can’t change any styles.

Fix linting errors

---

services/drupal/web/themes/epa_theme/source/_patterns/07-pages/detail-pages/event.twig
services/drupal/web/themes/epa_theme/templates/content/node--event--full.html.twig

this PR moves event registration from the bottom to below the date field and above the location field. 
it adds also adds registration + event host fields to pattern lab.

EPAD8-1848 relocate event registration

---

services/drupal/default.conf

This PR corrects a typo where I specified the wrong directive.

EPAD8-1900: Use correct directive

---

services/drupal/config/sync/editoria11y.settings.yml

adds the site header and footer to editoria11y's ignore settings

Epad8 2024 editorally tweaks

---

services/drupal/config/sync/core.entity_form_display.node.event.default.yml

https://forumone.atlassian.net/browse/EPAD8-2064

Adding MST Phoenix to event timezones

---

services/drupal/web/modules/custom/epa_workflow/epa_workflow.module

https://forumone.atlassian.net/browse/EPAD8-2095

Update 508 link in Assertion

---

services/drupal/config/sync/field.field.node.event.field_location.yml

https://forumone.atlassian.net/browse/EPAD8-2072

Add additional locations (MX,CA) to events

---

terraform/infrastructure/s3.tf
terraform/infrastructure/variables.tf

This PR adds the Terraform code necessary for optional replication of the S3 uploads buckets.

EPAD8-2168: Add replication configuration

---

.gitlab-ci.yml

Plan jobs are failing, attempting to correct with higher timeout

Increasing timeout of plan step

---

terraform/infrastructure/load_balancer.tf
terraform/infrastructure/s3.tf

This PR removes unused buckets that are easy to decommission. There are a few unused items that will take a bigger lift to remove, so I suggest postponing that to later.

EPAD8-2180: Remove unused buckets

---

services/drupal/redirect_301.map

Remove "composting" from redirect_301.map

---

services/drupal/web/themes/epa_theme/source/_patterns/03-uswds/_index.scss
services/drupal/web/themes/epa_theme/source/_patterns/03-uswds/collection/_collection-item.scss

This PR makes USA Collection Items have a max width of 100% so they're the same size as their parent & pagination.

EPAD8-2126 make collection items max width 100%

---

services/drupal/web/themes/epa_theme/source/_patterns/04-layouts/header/header.twig
services/drupal/web/themes/epa_theme/source/_patterns/05-components/menu/menu--main/_menu--main.scss
services/drupal/web/themes/epa_theme/source/_patterns/05-components/menu/menu--main/menu--main.twig
services/drupal/web/themes/epa_theme/source/_patterns/05-components/nav/nav--epa/_nav--epa.scss

This PR turns the EPA dropdown menu into the USWDS mega menu style.

Epad8 2086 uswds megamenu

---

services/drupal/web/themes/epa_theme/includes/navigation.inc
services/drupal/web/themes/epa_theme/source/_patterns/00-config/config.design-tokens.yml
services/drupal/web/themes/epa_theme/source/_patterns/05-components/_index.scss
services/drupal/web/themes/epa_theme/source/_patterns/05-components/breadcrumb/_breadcrumb.scss
services/drupal/web/themes/epa_theme/source/_patterns/05-components/breadcrumb/breadcrumb.md
services/drupal/web/themes/epa_theme/source/_patterns/05-components/breadcrumb/breadcrumb.twig
services/drupal/web/themes/epa_theme/source/_patterns/05-components/breadcrumb/breadcrumb.yml
services/drupal/web/themes/epa_theme/theme-settings.php

this PR adds the breadcrumb template to pattern lab & styles according to the figma. 
It also adds theme settings to turn on / off the page title in the breadcrumb string to epa theme.

EPAD8-2259 bredcrumb pattern

---

services/drupal/web/themes/epa_theme/source/_patterns/05-components/site-logo/_site-logo.scss

This PR makes the logo on the 404 page white to match all other pages.

EPAD8-2242 white logo on 404 page

---

services/drupal/web/themes/epa_theme/includes/navigation.inc

This PR adds the class needed for the sidebar group menu to render correctly in D10.

EPAD8-2298 fix sidebar styling for D10

---

terraform/webcms/drupal_schedule.tf

Updating cron expression to get past validation error

Updating cron expression

---

services/drupal/web/themes/epa_theme/source/_patterns/05-components/box/box--multipurpose/_box--multipurpose.scss
services/drupal/web/themes/epa_theme/source/_patterns/05-components/box/box--news/_box--news.scss

This PR adds a dark background style for the news box and the multipurpose box.

EPAD8-2007 dark bg changes for multipurpose and news boxes

---

services/drupal/config/sync/core.entity_view_display.node.faq.teaser.yml
services/drupal/config/sync/core.entity_view_display.node.public_notice.teaser.yml

This PR sets the config for frequently asked questions and public notices description on collection items to be trimmed with a "..." at the end.

Epad8 2125 dynamic list ellipsies

---

services/drupal/web/themes/epa_theme/source/_patterns/05-components/form-item/form-item--checkbox/_form-item--checkbox.scss

This PR makes the 508 wrap text form item full width so it wraps below the change state / revisions notes section.

Epad8 2364 508 wrap

---

services/drupal/web/modules/custom/epa_workflow/src/Icons.php
services/drupal/web/modules/custom/epa_workflow/src/Plugin/Block/EpaNodeTabsBlock.php

Initial implementation for the node tabs.

[EPAD8-2381] Node tabs

---

services/drupal/composer.lock

Incorporates the following PRs:
- https://github.com/USEPA/webcms/pull/1057
- https://github.com/USEPA/webcms/pull/1083
- https://github.com/USEPA/webcms/pull/1194
- https://github.com/USEPA/webcms/pull/1259

[EPAD8-2389] Dependabot prs

---

services/drupal/web/themes/epa_theme/source/_patterns/07-pages/standalone-template.twig

Ensuring that the standalone links match the links in the application

Update Accessibility statement link in standalone footer

---

services/drupal/web/themes/epa_theme/source/_patterns/05-components/hero-slideshow/_hero-slideshow.scss

Fixes full width bug on focus for carousel buttons on mobile

EPAD8-2427 carousel button mobile focus width

---

services/drupal/composer.json
services/drupal/composer.lock
services/drupal/config/sync/core.extension.yml
services/drupal/config/sync/push_framework.settings.yml

- Updates danse_moderation_notifications with push framework token support.
- Installs and enables `token_or` module
- Updates push framework email channel configuration

Epad8 2428 push framework tokens

---

services/drupal/web/modules/custom/epa_snapshot/src/EventSubscriber/EpaSnapshotSubscriber.php
services/drupal/web/sites/default/settings.php
services/drupal/web/sites/default/settings.snapshot.php

[EPAD8-2518] Exclude additional routes from snapshot [EPAD8-2518] Add snapshot settings file
[EPAD8-2515] Add search functionality to snapshot
[EPAD8-2519] Exclude listing pages from snapshot

[EPAD8-2518] Update snapshot implementation

---

services/drupal/composer.patches.json
services/drupal/web/sites/default/settings.local.env.php
services/drupal/web/themes/epa_theme/source/_patterns/05-components/figure/_figure.scss
services/drupal/web/themes/epa_theme/source/_patterns/05-components/figure/figure--large/_figure--large.scss
services/drupal/web/themes/epa_theme/source/_patterns/05-components/figure/figure--medium/_figure--medium.scss
services/drupal/web/themes/epa_theme/source/_patterns/05-components/figure/figure--original/_figure--original.scss
services/drupal/web/themes/epa_theme/source/_patterns/05-components/figure/figure--small/_figure--small.scss
services/drupal/web/themes/epa_theme/source/_patterns/05-components/figure/figure--thumbnail/_figure--thumbnail.scss

I merged #1448 into this branch in order to fix a merge conflict, so that PR should be reviewed first.

EPAD8-2508: Image alignment in CKEditor 5

---

services/drupal/web/modules/custom/epa_snapshot/src/EventSubscriber/EpaSnapshotSubscriber.php

- Strips www.epa.gov from the URLs in the EPA snapshot content.
- Refines the form exclusion for the snapshot home

[EPAD8-2548] Strip the EPA host url explicitly

---

services/drupal/composer.patches.json

[EPAD8-2524] Resolving issue with missing styles in vertical tabs

---

.buildkite/feature.yml
.buildkite/webcms.yml

This PR contains the necessary changes to build on our new Buildkite stacks, and is a prerequisite for rolling out ARM support in our build environment.

Switch to new Buildkite stacks

---

services/drupal/web/modules/custom/epa_core/epa_core.module

…ts to the sidebar field (field_paragraphs_1) on basic pages.

[EPAD8-2632] Fixing link list in sidebar field

---

services/drupal/config/sync/core.extension.yml
services/drupal/web/modules/custom/epa_alerts/src/Plugin/Block/InternalAlertsBlock.php
services/drupal/web/modules/custom/epa_alerts/src/Plugin/Block/PublicAlertsBlock.php
services/drupal/web/themes/epa_theme/js/src/epa-alerts.es6.js

Revert "[EPAD8-2656] Adding logic to resolve issue where the drupalsetting fo…"

---

services/drupal/config/sync/core.extension.yml
services/drupal/web/modules/custom/epa_alerts/src/Plugin/Block/InternalAlertsBlock.php
services/drupal/web/modules/custom/epa_alerts/src/Plugin/Block/PublicAlertsBlock.php
services/drupal/web/themes/epa_theme/js/src/epa-alerts.es6.js

Revert "Revert "[EPAD8-2656] Adding logic to resolve issue where the drupalsetting fo…""

---

services/drupal/web/modules/custom/epa_web_areas/src/Plugin/views/filter/UsersGroupsFilter.php

Avoids dynamic property deprecation warning.

EPAD8-2659 remove unneeded code that sets the current display

---

services/drupal/web/themes/epa_theme/includes/field.inc

https://forumone.atlassian.net/browse/EPAD8-2666
I'd like to learn the next step of pushing this to a branch that will then be delivered to EPA

Change "&" to "and" for speeches plural bundle

---

services/drupal/config/sync/node.type.public_notice.yml

https://forumone.atlassian.net/browse/EPAD8-2667

Update PN help text on add new content page

---

services/drupal/config/sync/views.view.group_moderated_content.yml
services/drupal/config/sync/views.view.moderated_content.yml

https://forumone.atlassian.net/browse/EPAD8-2668

Remove "author" from help text on content dashboards

---

services/drupal/composer.json
services/drupal/composer.lock

Hello Mike, I just updated the Configuration Split Module from 8.x-1.9 to 1.10. Please review it and let me know if you further questions. Thanks.

webcms-13 Update Configuration Split Module from 8.x-1.9 to 1.10

---

services/drupal/composer.json
services/drupal/composer.lock

Updated Access_unpublished to 8.x-1.6

---

services/drupal/composer.json
services/drupal/composer.lock

block_in_page_not_found: 4.3
block_in_page_403: 2.0.1 (probably not needed since we redirect 403s to 404s)

Update both "block in page" plugins

---

services/drupal/composer.json
services/drupal/composer.lock
services/drupal/config/sync/siteimprove.settings.yml

Also update config to uncheck "Use latest experience"

Update Siteimprove and its config

---

services/drupal/composer.json
services/drupal/composer.lock
services/drupal/config/sync/core.extension.yml

Remove module_filter

---

services/drupal/composer.lock
services/drupal/composer.patches.json
services/drupal/web/modules/custom/epa_core/epa_core.module

Also deleted web/modules/custom/facets_pretty_paths and patches for that module

Updated facets to 2.0.10

---

services/drupal/web/modules/custom/epa_alerts/epa_alerts.info.yml
services/drupal/web/modules/custom/epa_breadcrumbs/epa_breadcrumbs.info.yml
services/drupal/web/modules/custom/epa_es_auth/epa_es_auth.info.yml
services/drupal/web/modules/custom/epa_forms/epa_forms.info.yml
services/drupal/web/modules/custom/epa_layouts/epa_layouts.info.yml
services/drupal/web/modules/custom/epa_links/epa_links.info.yml
services/drupal/web/modules/custom/epa_media/epa_media.info.yml
services/drupal/web/modules/custom/epa_metatag/epa_metatag.info.yml
services/drupal/web/modules/custom/epa_rss/epa_rss.info.yml
services/drupal/web/modules/custom/epa_s3fs/epa_s3fs.info.yml
services/drupal/web/modules/custom/epa_viewsreference/epa_viewsreference.info.yml
services/drupal/web/modules/custom/epa_web_areas/epa_web_areas.info.yml
services/drupal/web/modules/custom/f1_sso/f1_sso.info.yml
services/drupal/web/modules/custom/media_inline_embed/media_inline_embed.info.yml
services/drupal/web/modules/custom/view_mode_select_by_token/view_mode_select_by_token.info.yml

Basically changing core_version_requirement to "^10 || ^11"

Update all custom modules that Rector identifies as clean
